### PR TITLE
Fix for numpy 1.24.0

### PR DESCRIPTION
**Pull request by Roozter**

### CODE REVIEW

**Comment by apockill** [comment]
This fix appears to be in the `humble` branch already. If https://github.com/Box-Robotics/ros2_numpy/pull/7 is merged, your PR will not be necessary.

**Comment by Roozter** [comment]
#7 is only updating the rolling branch I believe

**Comment by apockill** [comment]
My apologies, I completely misread the branches this is merging. You are right!

**Comment by tpanzarella** [comment]
I believe this PR is satisfied by the mainline at this point. Please re-open if necessary.

**Pull request closed without merging**
